name = "Chromaticracked"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544633f224c8f3630deaeef68d09b67d70ad28d072e9224043e2eca1d8223d49"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
