name = "Chromaticracked"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2b9e596ce6ea35864d24620e3787c4a8d872a9095d3d6daa3fa1f53be01cbe1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
