name = "Chromaticracked"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d8e89f9efe0688626bef2ebbdf4dfb01e097c244dd22bc2ca15dc5a3c702640"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
